=== techno-optimist/p42-prizes/problems/mertens-lp-ceiling-k12000/solution.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://p42.xyz/problems/mertens-lp-ceiling-k12000/solution.schema.json",
  "x-p42-max-bytes": 524288,
  "type": "object",
  "required": ["K", "M", "denom_pow", "printed_decimal", "y_hash_sha256", "m", "Y"],
  "additionalProperties": false,
  "properties": {
    "K": { "const": 12000 },
    "M": { "const": 120000 },
    "denom_pow": { "const": 48 },
    "source": { "type": "string" },
    "printed_decimal": {
      "type": "string",
      "pattern": "^0\\.[0-9]{25}$"
    },
    "y_hash_sha256": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "m": {
      "type": "array",
      "minItems": 1,
      "maxItems": 20000,
      "items": {
        "type": "integer",
        "minimum": 1,
        "maximum": 119999
      }
    },
    "Y": {
      "type": "array",
      "minItems": 1,
      "maxItems": 20000,
      "items": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9223372036854775807
      }
    }
  }
}

=== techno-optimist/p42-prizes/problems/mertens-lp-ceiling-k12000/examples/certificate-k12000.json
{"K":12000,"M":120000,"Y":[139901970679563,46824702894009,23548415083207,14022051672526,9573733800646,6489579999280,5194406985692,3898376726929,3163500851753,2432118438526,2254136652092,1746481796544,1616342548138,1349802404502,1115544601180,967375606833,966885780899,807682865744,817255963768,695786769956,574263249809,513007834645,510343358883,474211610508,451563228367,412756148166,340439886758,334252216250,331888736880,293918460769,323817124096,286444656389,250017065106,257086672760,192511707246,179682713191,204660591491,188704908984,179832765874,153676259221,166764373765,153611164276,170669081886,143304944202,121119296876,134409330213,144233938900,127000463411,119394221125,114612542790,105072157883,90022765145,107394531888,100713454763,88587070705,77378418617,72620605130,60187091707,85524463643,70784047134,80099890181,84447803847,76925045254,71566943093,62427216341,56063708316,65503288650,52667938326,52152067676,54644054553,62940599787,55308401868,60358504790,61408088551,58098605061,46069146663,38408366250,39930715664,41074910666,35119541916,48282407463,42560356073,51606897180,38685706728,40808195604,40779280370,37162088743,34605808100,39361548271,38258165344,33950335560,26761286733,26060740191,28197296305,27743013448,22435627794,31229999593,25627239674,18429057375,19392968870,23415271078,20659053365,29093344958,24635437649,27358974435,24503233271,29491211753,31244299713,31412765437,29658715076,29766065562,24928807468,25992286450,25678988426,26221255103,28084062023,23509151496,20060627442,17877461742,14965887249,16173986927,15250819726,17772198790,15423307065,13975586941,10726897621,14235819675,12753744457,13933635120,13310748256,18983975048,21431558450,19603581887,16074102850,18562424190,15208898446,15618979562,12547494354,13889216421,14858549462,14375400322,12949094951,13952878432,12119001988,11396838533,12557400205,11594929215,9470109543,11772906496,13199070733,14069399598,12668996682,11492537768,12661352741,10653248110,9550074227,12251198734,11616361101,10286522311,10687616929,11638690428,7446936140,11144149191,10130015903,10338375468,7923240894,10081347509,10499771978,13334306814,11180882978,11062547044,9990308252,10208552236,9755104142,9715011827,8438584958,6663714463,5701590125,9395680165,9497925211,13167177791,10347389115,8309705476,8025302011,8566006835,9422467639,9419852076,8335434189,7364947597,5176350949,6501074651,6259518744,7824976139,6788845081,5330010056,5714183929,8990478450,8457316748,10759593396,10556848296,9899588274,9942114157,9816617440,8705284151,6506089999,6858481604,5734370854,5679730094,6819391362,6107369195,9592454601,7565709056,6654654536,3702702244,3898976908,4069359914,3143020317,2736514939,3335486997,2565342497,2671622663,2396415847,4026182082,3649845568,3308023691,4411744711,5613397987,4980649933,5811562701,4864826237,4789318561,5489728595,6471304634,6002255642,5408695886,4277138991,3439330486,3475472307,5920499500,4418783328,5460051804,6263995128,7007310330,6188362905,5782176711,6483233416,6451352958,5011395645,5322763436,3531607035,4342645461,3766588819,3551746505,4562356003,4152224761,3208238039,4757613629,3766837000,3470805577,3976510711,4131138524,3776681191,4325740765,2886685376,2329066782,4065427727,3625035151,3202502398,3885665816,3655882471,3455749218,4071737563,3539102453,2766704788,3692603453,3159684182,4869156287,5366619553,5020480107,4184878047,4619094600,3413725609,5353008635,5214601386,4871100717,4586465777,3957903202,3611453874,4444731352,4259545053,5162499349,3555634084,3520508932,3307628226,3898697835,3458082728,3502502207,2961748388,2522688700,4141655365,4385457611,4558617411,3963385428,3331337204,2388157664,2531699416,2829269104,1535142788,1856845637,2091528524,3186472890,2573594350,2715221699,2829111073,3487532966,2966618850,3605942677,3616220534,3811403526,3392064067,4155630456,3590944588,1900026192,1535651845,2038533045,1282808181,1330801868,1493589381,1802227091,1085351317,1881580868,1619956458,1531042974,2057647406,1529735961,2576845074,3245964324,2082955655,858944158,2003285578,1620114544,691694621,1261627074,1475429301,958891364,955595411,1260792668,912809052,825294353,212428831,1149472460,2622657206,3202031699,3918850891,3236967560,3074488031,3101231900,2291251822,2536125077,2896621402,3933349162,2785014951,2266133598,1362351556,1221562005,1191871690,2222560728,2546525930,3171254437,2957368532,2084694742,1269386196,1893382526,1215719241,1076769359,831777726,1474925070,1838615328,2046134625,1867594411,1920906285,1615602944,2970923495,2993181014,2974955058,2554728183,2399146810,2364515430,2951196915,2991466008,2557304528,2758455256,2261428876,1869200843,1618999286,1918020595,2380413073,1773609215,1826607430,2329369619,3068166558,2718991086,2717923733,2001075721,1155843515,940487807,844888593,1168945529,2128695232,2370643660,2222196057,2071951788,1419151226,1634267151,1112722952,1094248262,770595286,433981718,1053060146,1351942395,2080083623,1796589721,2001500763,2167711507,1748356613,1459507796,442993157,30676414,259957370,975431354,1701647375,1333246277,2063055443,1774938966,1844440020,1682006644,1113338935,604141069,1235015236,1474969568,958729091,937523492,1249801206,1274424096,842891846,1106156063,1049892048,618006720,1514212871,1547015617,1706754738,1509562608,1218582221,1205143039,1441726923,1301229167,1218527105,647956222,702071521,1172660661,2220779487,1956032410,2414652499,2465576195,2229976034,2303247183,2376685312,2410517917,2202474055,2183722727,1736639060,1166518271,733964971,792027799,1063882576,956272282,1219418209,1566500397,1663067768,1464773809,1587162715,1539437725,923766598,917053356,436698178,862555206,1558752117,1579780831,1536246948,1474452392,1239448460,1214984503,1320343636,1295066139,1467061401,1148934141,1045256870,793689136,1295615260,1518789871,1147748420,1152691736,1827909209,1644116416,1608032365,1772129782,1459309244,1423620117,1848311584,1488427982,1450519646,1546140473,1356608855,1132668802,638299840,776740718,513779020,352376233,284848475,216994652,794114249,538082175,1391291909,1524697596,1406540023,1394016809,1243603961,1192481597,885851522,791537544,660140681,429768188,839994121,1095928167,766921283,599595280,830953247,549678032,646402516,674479479,994554050,800602645,930524268,737479154,717663207,555358914,1041017872,1133499431,965050598,919764371,808890626,676619667,732325438,399284754,442395833,435054432,548452133,379875709,43343995,340460431,333892485,394902099,182363250,318330893,324199100,433287107,90726455,258240474,602173452,649591913,1145784322,1130499446,1136546244,1166349578,1095117027,667327479,898517675,281618306,442820090,476413633,318781672,865696570,531523289,603733090,420727519,461142213,1089197317,742350896,873738650,712848914,773727460,836727177,900527127,868487185,379229058,327385729,276727495,448372171,218524158,437624276,249174011,410043139,329169698,430099555,143672015,877188377,724191772,968294580,1109480555,819829525,801914068,1165139219,921580889,907886978,732930743,962865843,674145339,1093832775,1020561625,1152110431,1151008915,1202609083,1268267287,1134398647,962335491,1227363345,1214807820,585202766,387481489,623408685,584438691,831199177,718187869,556666194,753439369,723232232,776912980,858471061,773601312,696585886,833124757,1084612368,1239271245,1342590442,1273099489,1384340858,1391742240,1186723292,1083301338,917926903,408694245,783148434,887845450,891129549,855268488,651102800,713205530,853789820,376607321,818004207,610746622,1063670307,1029437485,754265610,837962749,484667186,610461707,364012558,346213442,372038441,323763060,826492818,666842962,562803698,576877075,1007965468,1014686922,1118444354,1048824805,840591167,671983722,682059626,634538051,739138135,669433229,817688919,928351017,888225525,979908126,1043401771,1302093515,1210017175,1095302207,1019645796,1104733802,939354643,889069627,608365324,461293355,698521941,632069389,425441245,351885878,525563105,420924306,363704682,211263287,369727200,568032910,711037666,792791505,731938397,576571887,527753537,527916321,439297984,583308082,711037713,732275982,695515347,451820073,421317421,562163443,383669752,176927146,571326546,508886372,747208099,777306968,391596189,388915838,464631317,307932738,390535283,421752246,121319855,168688631,440660411,140282792,214011820,300628770,605819980,523410081,547052599,735000788,528088854,618887000,403029336,249124494,551170443,489689532,432152281,359309554,369004108,274103599,504133235,604063914,604776329,521065020,807958961,502871412,470616665,453391348,468345426,676095083,418863324,462950993,559482346,638042849,760327215,739780707,1046936131,807226296,787164231,468421814,300019074,372129447,82512259,61477497,11228227,322435103,493213919,264686407,535383193,646087027,773529639,674278446,723492942,573480878,428427729,587414755,591871442,23604870,177732019,35192983,23296766,170109614,244855909,181662297,289862670,133952697,126031508,80777878,211924246,167403122,512017815,200580408,181052007,122829316,334974671,101800424,409520234,498349674,345186572,317629762,469488946,481608848,490725978,526991758,473874005,464192447,764765563,593146217,421978338,415757742,406172211,317455870,499683178,319181617,325074915,299494050,267976395,489183833,371301544,193560521,519326708,555428756,485289808,528959482,668138670,383680264,565838473,435147459,333570185,106176523,190393371,188914248,175924076,441938496,266051844,462288769,592866563,923308033,747700164,770294113,374237240,298374386,420639988,271206832,511867566,515142483,371992593,359810641,589342671,721487116,759347958,717216429,791784821,773086282,855217237,911456681,787423233,821735318,824656128,702019199,616684170,588302501,621330662,796103435,820378355,614603107,652338698,418691550,291247767,121546090,173463545,147705057,5209854,128052995,136243526,124660058,295573977,280946773,248629485,195184220,178330209,405043994,361563629,161034726,167510940,314846085,408950566,204466341,231488827,216055153,242584520,64453467,71926094,73992778,181571459,112821959,110956001,285858167,231451358,309916455,253651249,240628079,458970145,327964015,262447655,378912385,342
